"""Generate synthesis/capability-matrix.md from projects/*/facts.yaml.

The matrix is derived, never hand-edited. Hand-maintaining it guarantees drift
from the teardowns by about project four.

    ./.venv/bin/python tools/build_matrix.py

Writes synthesis/capability-matrix.md. Rows are the capability lines defined in
CAPABILITIES below; each maps to the probe that decides it.
"""

from __future__ import annotations

from datetime import date, timezone, datetime
from pathlib import Path

from probes import (REPO_ROOT, load_facts, load_probes, probe_order,
                    project_slugs)

OUTPUT = REPO_ROOT / "synthesis" / "capability-matrix.md"

# Deliverable 1 rows. Each is (label, deciding probe id).
# Keep this short: the matrix is a gap-finder, not a full transcript of facts.
CAPABILITIES: list[tuple[str, str]] = [
    ("Stable agent identity", "D1"),
    ("Identity survives restart", "D2"),
    ("Agent versioning", "D4"),
    ("Agent registry", "D5"),
    ("Agent discovery", "D6"),
    ("Declarative manifest", "D10"),
    ("Task separate from Run", "A4"),
    ("Messages first-class", "A6"),
    ("Artifacts first-class", "A7"),
    ("Durable execution", "C1"),
    ("Checkpoint / resume", "C3"),
    ("Crash recovery", "C7"),
    ("Durable timers", "C10"),
    ("Mid-flight upgrade", "C12"),
    ("Foreign agent hosting", "E3"),
    ("Observable tool calls", "E5"),
    ("Cancellation", "E7"),
    ("Agent mailbox", "F5"),
    ("Durable delivery", "F6"),
    ("Capability routing", "F11"),
    ("Human as principal", "G1"),
    ("Shared workspace", "G2"),
    ("HITL approval", "G5"),
    ("Long-term agent memory", "H1"),
    ("Shared memory", "H3"),
    ("Memory permissions", "H4"),
    ("Capability abstraction", "I2"),
    ("Policy interception", "I8"),
    ("Agent authN identity", "J1"),
    ("Tenant isolation", "J7"),
    ("Audit log", "J9"),
    ("Sandbox", "K1"),
    ("Pluggable sandbox", "K9"),
    ("Scheduled triggers", "L3"),
    ("Subagents first-class", "L6"),
    ("OpenTelemetry", "M3"),
    ("Stable event schema", "M4"),
    ("Cost accounting", "M5"),
    ("Multi-tenancy in OSS", "N8"),
    ("MCP", "O5"),
]

GLYPHS = {
    "first_class": "●",
    "implicit": "◐",
    "absent": "○",
    "unknown": "?",
    "first_class_answer": "●",
    "inferable": "◐",
    "undefined": "○",
    None: "·",
}

LEGEND = (
    "`●` first-class  ·  `◐` implicit / inferable  ·  "
    "`○` absent  ·  `?` unknown  ·  `·` not yet examined"
)


def short(slug: str, width: int = 11) -> str:
    """Abbreviate a slug for a column header."""
    parts = slug.split("-")
    if len(slug) <= width:
        return slug
    if len(parts) > 1:
        candidate = "".join(p[0] for p in parts).upper()
        if len(candidate) >= 2:
            return candidate
    return slug[:width]


def build() -> str:
    probes, scenarios, _ = load_probes()
    slugs = project_slugs()
    facts = {s: load_facts(s) for s in slugs}

    # Deep projects first, then targeted, then recon; alphabetical within rank.
    rank = {"deep": 0, "targeted": 1, "recon": 2}
    slugs.sort(key=lambda s: (
        rank.get((facts[s].get("project") or {}).get("depth"), 3), s
    ))

    headers = [short(s) for s in slugs]
    widths = [max(len(h), 5) for h in headers]
    label_w = max((len(c) for c, _ in CAPABILITIES), default=20)

    lines: list[str] = []
    lines.append("# Deliverable 1 — Capability Matrix")
    lines.append("")
    lines.append(
        f"<!-- GENERATED by tools/build_matrix.py on "
        f"{datetime.now(timezone.utc).date().isoformat()}. Do not edit by hand. -->"
    )
    lines.append("")
    lines.append(
        "Derived from `projects/*/facts.yaml`. Regenerate with "
        "`./.venv/bin/python tools/build_matrix.py`."
    )
    lines.append("")
    lines.append(LEGEND)
    lines.append("")

    if not slugs:
        lines.append("_No projects with `facts.yaml` yet._")
        lines.append("")
        return "\n".join(lines)

    # Column key, since headers are abbreviated.
    lines.append("| Column | Project | Depth | Evidence | Runtime class |")
    lines.append("|---|---|---|---|---|")
    for slug, header in zip(slugs, headers):
        project = facts[slug].get("project") or {}
        lines.append(
            f"| `{header}` | {project.get('name', slug)} "
            f"| {project.get('depth', '?')} "
            f"| {project.get('evidence_class', '?')} "
            f"| {project.get('runtime_class', '?')} |"
        )
    lines.append("")

    header_row = (
        f"| {'Capability'.ljust(label_w)} | "
        + " | ".join(h.ljust(w) for h, w in zip(headers, widths))
        + " | Our decision |"
    )
    sep_row = (
        f"|{'-' * (label_w + 2)}|"
        + "|".join("-" * (w + 2) for w in widths)
        + "|---|"
    )
    lines.append(header_row)
    lines.append(sep_row)

    for label, pid in CAPABILITIES:
        cells = []
        for slug, width in zip(slugs, widths):
            entry = ((facts[slug].get("probes") or {}).get(pid)) or {}
            verdict = entry.get("verdict") if isinstance(entry, dict) else None
            cells.append(GLYPHS.get(verdict, "·").ljust(width))
        lines.append(
            f"| {label.ljust(label_w)} | " + " | ".join(cells) + " |  |"
        )

    lines.append("")
    lines.append("## Probe reference")
    lines.append("")
    for label, pid in CAPABILITIES:
        question = probes.get(pid) or scenarios.get(pid, "(unknown probe)")
        lines.append(f"- **{label}** — `{pid}`: {question}")
    lines.append("")

    # Coverage, so gaps in the *research* are as visible as gaps in the products.
    total = len(probes) + len(scenarios)
    lines.append("## Research coverage")
    lines.append("")
    lines.append("| Project | Answered | Of | Coverage | Unknowns |")
    lines.append("|---|---|---|---|---|")
    for slug in slugs:
        entries = facts[slug].get("probes") or {}
        answered = sum(
            1 for e in entries.values()
            if isinstance(e, dict) and e.get("verdict") not in (None, "unknown")
        )
        unknowns = sum(
            1 for e in entries.values()
            if isinstance(e, dict) and e.get("verdict") == "unknown"
        )
        pct = 100.0 * answered / total if total else 0.0
        lines.append(f"| {slug} | {answered} | {total} | {pct:.0f}% | {unknowns} |")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build())
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
